/** Polish UI strings used by E2E tests (default locale). */
export const pl = {
  workspace: {
    title: "Cicha lokalna przestrzeń do powrotu do kontekstu pracy.",
    open: "Otwórz folder",
    create: "Utwórz przestrzeń",
    sample: "Utwórz przykładową przestrzeń",
    name: "Nazwa przestrzeni",
  },
  module: {
    potoki: "Potoki",
    harbor: "Przystań",
  },
  harbor: {
    title: "Przystań",
    newPier: "Nowy pomost",
    newCard: "Nowa karta",
    editCard: "Edytuj kartę",
    copy: "Kopiuj",
    copied: "Skopiowano",
    edit: "Edytuj",
    delete: "Usuń",
    back: "Przystań",
    pierNamePlaceholder: "Nazwa pomostu",
    pierDescriptionPlaceholder: "Krótki opis pomostu",
    cardTitlePlaceholder: "Tytuł karty",
    cardContentPlaceholder: "Treść karty",
    syntax: "Składnia",
    searchCards: "Szukaj kart...",
    deleteCardTitle: "Usunąć kartę?",
  },
  dashboard: {
    title: "Do czego chcesz wrócić?",
  },
  timeline: {
    back: "Przegląd",
    entryTitle: "Tytuł wpisu",
    editTitle: "Tytuł wpisu",
    addEntry: "Dodaj wpis",
    edit: "Edytuj wpis",
    delete: "Usuń wpis",
    save: "Zapisz",
    attachNote: "Dodaj notatkę",
    unlinkFile: "Odłącz plik od wpisu",
    typeWorkLog: "praca",
  },
  stream: {
    sampleAi: "R&D: lokalna integracja AI",
    test: "Testowy potok",
    legacy: "Legacy local AI context",
    sparse: "Sparse stream",
  },
  notes: {
    titlePlaceholder: "Tytuł notatki",
    save: "Zapisz notatkę",
    edit: "Edytuj notatkę",
    removeFromEntry: "Usuń notatkę z wpisu",
    removeFromEntryConfirm: "Usuń z wpisu",
    markdownEditor: "Edytor Markdown",
  },
  markdown: {
    bold: "Pogrubienie",
    italic: "Kursywa",
    heading2: "Nagłówek 2",
    bulletedList: "Lista punktowana",
    link: "Link",
  },
  settings: {
    title: "Ustawienia",
    english: "English",
    englishDialog: "Settings",
  },
  common: {
    save: "Zapisz",
    delete: "Usuń",
    cancel: "Anuluj",
    closeDialog: "Zamknij okno",
  },
} as const;
